import "dotenv/config";

import { OpenAI } from "openai";

const client = new OpenAI();

async function horoscope() {
  function getHoroscope(sign) {
    return `${sign}: Next tuesday will be awefull`;
  }

  const tools = [
    {
      type: "function",
      name: "get_horoscope",
      description: "Todays Horoscope for the astrological sign",
      parameters: {
        type: "object",
        properties: {
          sign: {
            type: "string",
            description: "An astrological sign like Taurus or Aquarius",
          },
        },
        required: ["sign"],
        additionalProperties: false,
      },
      strict: true,
    },
  ];
  const inputs = [{ role: "user", content: "What is my horoscope, I am Leo?" }];

  let response = await client.responses.create({
    model: "gpt-5.6-luna",
    input: inputs,
    tools: tools,
  });

  console.log("horoscope: ", response.output);
  inputs.push(...response.output);

  for (const item of inputs) {
    if (item.type !== "function_call") continue;

    if (item.name == "get_horoscope") {
      const { sign } = JSON.parse(item.arguments);
      const horoscope = getHoroscope(sign);

      inputs.push({
        type: "function_call_output",
        call_id: item.call_id,
        output: horoscope,
      });
    }
  }

  console.log("Final input: ", JSON.stringify(inputs, null, 2));

  response = await client.responses.create({
    model: "gpt-5.6-luna",
    instructions: "Respond only with a horoscope generated by a tool.",
    tools: tools,
    input: inputs,
  });

  console.log("\nFinal output: ", response.output_text);
}

async function customerSupport() {
  const MODEL = "gpt-5.6-luna";
  function getCustomerProfile(customerId) {
    return `Customer Profile for ${customerId}: Name: John Doe, Tier: Platinum, Status: Active.`;
  }

  function listOpenOrders(customerId) {
    return `Open orders for ${customerId}: Order #1002 (Pending Shipment), Order #1045 (Processing).`;
  }

  function getCustomerLifetimeValue(customerId) {
    return `Customer Lifetime Value for ${customerId}: $12,450.00 USD.`;
  }

  const tools = [
    {
      type: "namespace",
      name: "crm",
      description: "CRM tools for customer lookup and order management",
      tools: [
        {
          type: "function",
          name: "get_customer_profile",
          description: "get the customer profile by customer ID",
          parameters: {
            type: "object",
            properties: {
              customer_id: {
                type: "string",
                description: "unique customer id",
              },
            },
            required: ["customer_id"],
            additionalProperties: false,
          },
        },
        {
          type: "function",
          name: "list_open_orders",
          description: "list of all the open ordres related to the user",
          //   defer_loading: true,
          parameters: {
            type: "object",
            properties: {
              customer_id: {
                type: "string",
                description: "unique id of the customer",
              },
            },
            required: ["customer_id"],
            additionalProperties: false,
          },
        },
        {
          type: "function",
          name: "get_customer_lifetime_value",
          description:
            "Fetch total spending data and financial health index for a customer.",
          parameters: {
            type: "object",
            properties: {
              customer_id: { type: "string" },
            },
            required: ["customer_id"],
            additionalProperties: false,
          },
        },
      ],
    },
  ];

  const inputs = [
    {
      role: "user",
      content:
        "Can you look up customer profile 'CUST-992' and also check if they have any open orders?",
    },
  ];

  const activeTools = [
    tools,
    { type: "tool_search" }, // Correct approach to activate dynamic query lookups
  ];

  let response = await client.responses.create({
    model: MODEL,
    input: inputs,
    tools: tools,
    // tools: activeTools,
    // tool_choice: "auto",
  });

  inputs.push(...response.output);

  for (const item of response.output) {
    if (item.type !== "function_call") continue;

    // console.log("item: ", item);

    if (item.name == "get_customer_profile") {
      const { customer_id } = JSON.parse(item.arguments);
      const customerDetails = getCustomerProfile(customer_id);

      inputs.push({
        type: "function_call_output",
        call_id: item.call_id,
        output: customerDetails,
      });
    }

    if (item.name == "list_open_orders") {
      const { customerId } = JSON.parse(item.arguments);
      const data = listOpenOrders(customerId);

      inputs.push({
        type: "function_call_output",
        call_id: item.call_id,
        output: data,
      });
    }

    if (item.name === "crm:get_customer_lifetime_value") {
      const { customer_id } = JSON.parse(item.arguments);
      const ltvData = getCustomerLifetimeValue(customer_id);

      inputs.push({
        type: "function_call_output",
        call_id: item.call_id,
        output: ltvData,
      });
    }
  }

  response = await client.responses.create({
    model: MODEL,
    input: inputs,
    tools: tools,
  });

  console.log("final output: ", response.output_text);
}

function init() {
  // horoscope();
  customerSupport();
}
init();
